### ISSUE TITLE
Typos and textual changes

### ISSUE THREAD

**Issue by EdwinCoster** [open-zaak/open-zaak-website#46]
If you want me to make the changes myself, please guide me to the relevant pages...

I only reviewed the dutch version of website

**General**

Use the same term or abbreviation to refer to components and standards such as 'de nationale API standaard voor zaakgericht werken', and 'ZGW-API's'. Also use the same part of term for the link/URL, use a link only once per paragraph and always link to the same page. So 'de nataional API blah blah' links to 'https://www.vngrealisatie.nl/producten/api-standaarden-zaakgericht-werken' and 'WGZ-API's' links to the GitHub repository.

**Main page** 

**First paragraph:**
Change to: 'OpenZaak is een productiewaardig API platform dat de API standaard voor zaakgericht werken implementeert (de ZGW API's. Met OpenZaak wordt het voor gemeenten mogelijk om veilige en betrouwbare diensten aan te kunnen bieden aan haar inwoners en bedrijven. Omdat OpenZaak gebruik maakt van de API standaard voor zaakgericht werken wordt het Uitwisselen van gegevens met andere gemeenten en/of applicaties eenvoudiger en veiliger. OpenZaak is open source software. Dat betekent dat iedereen vrij is deze software te hergebruiken of aan te passen aan haar wensen.'

**Zaken, Besluiten, Documenten en Open Notificaties**
Change to: 'OpenZaak implementeert alle ZGW-API’s en combineert deze met een gebruiksvriendelijke beheerinterface. Door gebruik te maken van de Open Notificaties standaard kunnen updates van zaken gepubliceerd worden naar andere systemen, zodat  die systemen wijzigingen in (de status van) de zaak kunnen volgen.'

Discuss: The statement that 'OpenZaak implements **all** ZGW-API's' is not entirely correct since during development of OpenZaak the set of API's has been extended with de Klanten, Contactmomenten and Verzoeken API's which are not available in OpenZaak (yet). So maybe this should be changed in 'alle ZGW-API's die per 01-01-2020 officieel zijn gereleased' or something.

**Catalogi & gemeentelijke selectielijsten**
Change to: 'OpenZaak bevat een beheerinterface voor catalogi en gemeentelijke selectielijsten. Zo kunt u gebruiken maken van standaard instellingen voor archivering van zaakgerichte gegevens bij het implementeren van uw proces en waar nodig deze aanpassen of aanvullen.'

**API Dashboard**
Change to: 'OpenZaak bevat een API dashboard dat inzicht geeft in het gebruik van OpenZaak. Zo krijgt u inzicht met welke frequentie en volume gegevens in OpenZaak worden geraadpleegd. Dit kan helpen bij het bijsturen en prioriteren bij het afhandelen van zaken.'

**Syteem integraties**
Change to: 'Omdat OpenZaak open source is kunnen leveranciers systeemintegraties met OpenZaak ontwikkelen voor hun document en content management systemen. Zo heeft u de vrijheid om gebruik te maken van bestaande of nieuwe applicaties in combinatie met OpenZaak. OpenZaak koppelt onder andere met Contezza DMS en Alfresco.'

**Page OpenZaak gebruiken**

The heading for the first paragraph is slightly indented to the right.

**OpenZaak gebruiken**
1st paragraph: 'OpenZaak is sinds begin 2020 beschikbaar voor gemeenten en ontwikkelaars in Nederland.'

**Voor ontwikkelaars**
Change: 'ontwikkeld door Nederlandse Vereniging van Gemeenten Realisatie (VNG Realisatie).' to 'ontwikkeld in opdracht van de Nederlandse Vereniging van Gemeenten (VNG Realisatie)'.

3rd paragraph: 'Om het meeste uit OpenZaak te halen, moet OpenZaak verbinding maken met andere systemen of componenten. Voornamelijk systemen voor het afhandelen van het proces zoals een app voor een melding openbare ruimte, een processysteem voor het afhandelen van vergunningen of een generiek zaakafhandelcomponent. Voorbeelden van dergelijke systemen zijn MyApp of apps voor MOR-rapporten.'

4th paragraph: change 'landelijke Zaak Gericht Werken API' to 'ZGW-API's'.

5th paragraph: 'OpenZaak wordt als open source project verder ontwikkeld door een open en actieve gemeenschap van gemeenten, leveranciers en softwareontwikkelaars en verwelkomt iedereen die wil deelnemen en bijdragen aan het verbeteren van OpenZaak. Leer hoe aan de slag kunt gaan en hoe u kunt bijdragen via onze GitHub repository.'

**Voor project- en product managers**
'Ben jij verantwoordelijk voor het beheren en ontwikkelen van zaakgericht werken binnen uw gemeente en wil je mee helpen vorm te geven aan de toekomstige ontwikkeling van OpenZaak?'

Add line feed

'Dan kun je op de volgende manieren bijdragen:'
- Abonneer u op de OpenZaak community mailinglist
- Kijk naar de feature request backlog.
- Maak een nieuw feature request aan conform het feature request template
- Kondig je feature request aan op de OpenZaak community mailinglist

'Iedere maand komt de OpenZaak product steering groep bij elkaar om nieuwe feature requests te bespreken en te beslissen welke features verder ontwikkeld worden. Als je feature request wordt behandeld genomen ben je van harte uitgenodigd om jouw feature request nader toe te lichten.

'Wil je deelnemen in de product steering group? Of meer weten hoe besluiten in de OpenZaak community genomen worden neem dan contact met ons op.'

**Roadmap**
'Heb je ideeën over de toekomstige ontwikkeling van OpenZaak of mis je bepaalde functionaliteit? Kijk op de feature request backlog.

**OpenZaak Community**
OpenZaak is toegepast op de ontwerpprincipes van Common Ground, waardoor het snel, gemakkelijk en veilig geïmplementeerd kan worden door gemeenten in Nederland. OpenZaak is geoptimaliseerd voor de Haven referentie-implementatie, de standaard cloud-agnostische infrastructuur die wordt gebruikt voor alle Common Ground-initiatieven.

Common Ground staat voor een nieuwe, moderne, gezamenlijke informatievoorziening voor gemeenten. Data wordt gescheiden van werkprocessen en applicaties, en data wordt bij de bron ontsloten. In essentie is het uitgangspunt van Common Ground: een ingrijpende hervorming van de informatievoorziening, die vraagt ​​om een ​​nieuwe manier van samenwerken tussen gemeente en markt.

**Wie is de eigenaar van de OpenZaak?**
'De OpenZaak-code is openbaar en er is niet zozeer een eigenaar van OpenZaak, maar wel een maintainer. OpenZaak is in eerste instantie ontwikkeld door Maykin Media BV, in opdracht van een aantal gemeenten onder leiding van Dimpact. De gemeenten zijn: Amsterdam, Rotterdam, Utrecht, Tilburg, Arnhem, Haarlem, 's-Hertogenbosch, Delft en een coalitie van Hoorn, Medemblik, Stede Broec, Drechteland, Enkhuizen (SED). De OpenZaak code wordt momenteel beheerd door de OpenZaak community en wordt gefaciliteerd door "Code Stewards" van de Foundation for Public Code.

**Samenwerken aan OpenZaak**
In samenwerking met Dimpact, de OpenZaak community en gefaciliteerd door de Foundation for Public Code, is OpenZaak toegankelijk gemaakt voor iedere gemeente in Nederland.

In overeenstemming met de principes van open source kan iedereen suggesties doen voor aanpassing of verbetering van de software; samen OpenZaak gebruiken en samen OpenZaak verbeteren. Op deze manier werken we samen aan het verbeteren van de informatiehuishouding, de kwaliteit van de online dienstverlening en de klanttevredenheid in onze gemeenten.

Wil je ook een bijdrage leveren aan OpenZaak? Lees hier meer over hoe je dat kunt doen.'

**Comment by felixfaassen** [comment]
Hi @EdwinCoster thank you so much for these improvements. We will pick them up and make the changes for the website. Great work!
